### ISSUE TITLE
Weather and some ability animations trigger the last used move animation

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#15] opened 2017-05-24 12:51 UTC
"Weather like Sunny Day and Rain Dance, as well as abilities that take place every turn like Speed Boost (as seen on Bugsy's Yanma) occasionally trigger the damage animation on the opponent's Pokemon. No damage is dealt obviously, but the animation and sound effect are present." ([via](https://www.pokecommunity.com/showthread.php?p=9613745#post9613745))

[Edit](https://www.pokecommunity.com/showthread.php?p=9613808#post9613808): "It looks like it recycles the last used animation. In this case it was the animation for taking damage, since Sentret was the last to attack."

Edit: 889182d96c99a9e5fcf5e4fd6a92847196dfaaa1 may have fixed this.

![image](https://camo.githubusercontent.com/721f3ed21e01756c0c4e9b257ec29e6150f0d675/68747470733a2f2f692e67697068792e636f6d2f6c31426751557a7669544d5745636769342e676966)

**Comment by FredrIQ** [comment] 2017-06-25 01:59
I found out the cause for this. Possibly other locations in the code still have issues, but for now I'm going to close this since I can't find any, nor has there been any beta reports about it.

**Closed by FredrIQ** 2017-06-25 01:59 UTC
Labels: battle engine, cosmetic, unconfirmed
