### ISSUE TITLE
Smeargle corrupts Pokémon colors in the PC and Wonder Trade

### ISSUE THREAD

**Issue by Acrozz** [roukaour/polishedcrystal#108] opened 2017-07-22 00:58 UTC
If I withdraw Smeargle to my party and then check it
![223](https://user-images.githubusercontent.com/23432421/28486946-085cbbbe-6e56-11e7-996b-652007b3b396.png)
The other Pokémon will have weird colors (including the ones in the boxes)
![ppc](https://user-images.githubusercontent.com/23432421/28486948-160e21ee-6e56-11e7-9aec-47e69732c522.png)
![ppc2](https://user-images.githubusercontent.com/23432421/28486979-7f8092f6-6e56-11e7-8c49-696a04cef8d4.png)
This bug resets only when checking stats of a Pokémon, entering a battle or using an HM.

Savefile here: https://drive.google.com/open?id=0B0V6QK6KcDvSdG5JX0MzTDI1c2M

**Comment by Acrozz** [comment] 2017-07-22 01:01
I also noticed that Smeargle has normal colors before being moved
![sc](https://user-images.githubusercontent.com/23432421/28487073-be0c99ec-6e57-11e7-97eb-710550e23110.png)

**Comment by roukaour** [comment] 2017-08-25 00:07
From Wisejustin2, a likely related bug: "Get a smeargle thats a different color, open its stats (mines a blue one) close out and wonder trade it, all the next pokes are blue till u open their stats again"

**Comment by roukaour** [comment] 2017-10-04 05:30
Duplicate of #133.

**Closed by roukaour** 2017-10-04 05:30 UTC
Labels: cosmetic
