### ISSUE TITLE
Speed Boost does not activate at the end of each turn

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#5] opened 2017-05-24 12:43 UTC
Sometimes Speed Boost does not activate at the end of a turn. It also does activate sometimes incorrectly, e.g. as a result of a faint+switch.

**Comment by roukaour** [comment] 2017-06-16 01:28
This might be fixed already.

**Comment by FredrIQ** [comment] 2017-06-25 01:57
Going to close this until someone decides to report it again. None of the testers have done and I can't reproduce it anymore.

**Closed by FredrIQ** 2017-06-25 01:57 UTC
Labels: battle engine, unconfirmed
